---
title: "So you want to harmonize data?"
author: "Marta Kołczyńska"
date: 2019-02-20T23:29:00
categories: ["R"]
tags: ["R", "Glenn Gould", "survey data harmonization", "interdisciplinarity"]
output: 
  blogdown::html_page:
    toc: true
    toc_depth: 4    
---

Harmonizing survey data is like writing a fugue.


<p><span style="color: #000080;"><em><strong>So You Want to Write a Fugue?</strong></em></span><br /><span style="color: #000080;"><strong>Glenn Gould</strong></span></p>

<iframe src="https://player.vimeo.com/video/29025438?title=0&byline=0&portrait=0" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>


<p><span style="color: #000080;"><em>So you want to write a fugue?</em></span><br /><span style="color: #000080;"><em>You've got the urge to write a fugue</em></span><br /><span style="color: #000080;"><em>You've got the nerve to write a fugue</em></span><br /><span style="color: #000080;"><em>So go ahead and write a fugue that we can sing</em></span><br /><span style="color: #000080;"><em>Pay no heed to what we've told you</em></span><br /><span style="color: #000080;"><em>Give no mind to what we've told you</em></span><br /><span style="color: #000080;"><em>Just forget all that we've told you</em></span><br /><span style="color: #000080;"><em>And the theory that you've read</em></span><br /><span style="color: #000080;"><em>For the only way to write one</em></span><br /><span style="color: #000080;"><em>Is just to plunge right in and write one</em></span><br /><span style="color: #000080;"><em>So just forget the rules and write one</em></span><br /><span style="color: #000080;"><em>Have a try, yes, try to write a fugue</em></span><br /><span style="color: #000080;"><em>So just ignore the rules and try</em></span><br /><span style="color: #000080;"><em>And the fun of it will get you</em></span><br /><span style="color: #000080;"><em>And the joy of it will fetch you</em></span><br /><span style="color: #000080;"><em>It's a pleasure that is bound to satisfy</em></span><br /><span style="color: #000080;"><em>So why not have a try?</em></span><br /><span style="color: #000080;"><em>You'll decide that John Sebastian</em></span><br /><span style="color: #000080;"><em>Must have been a very personable guy</em></span><br /><span style="color: #000080;"><em>But never be clever for the sake of being clever</em></span><br /><span style="color: #000080;"><em>For a canon in inversion is a dangerous diversion</em></span><br /><span style="color: #000080;"><em>And a bit of augmentation is a serious temptation</em></span><br /><span style="color: #000080;"><em>While a stretto diminution is an obvious solution</em></span><br /><span style="color: #000080;"><em>Never be clever for the sake of being clever</em></span><br /><span style="color: #000080;"><em>For the sake of showing off</em></span><br /><span style="color: #000080;"><em>It's rather awesome, isn't it?</em></span><br /><span style="color: #000080;"><em>And when you've finished writing it</em></span><br /><span style="color: #000080;"><em>I think you'll find a great joy in it (hope so)</em></span><br /><span style="color: #000080;"><em>Well, nothing ventured, nothing gained, they say</em></span><br /><span style="color: #000080;"><em>But still it is rather hard to start</em></span><br /><span style="color: #000080;"><em>Well, let us try</em></span><br /><span style="color: #000080;"><em>Right now? (yes, why not)</em></span><br /><span style="color: #000080;"><em>We're going to write a fugue</em></span><br /><span style="color: #000080;"><em>We're going to write a good one</em></span><br /><span style="color: #000080;"><em>We're going to write a fugue right now!</em></span></p>

