---
title: "Shiny app for exploring harmonized cross-national survey data (SDR v.1.0)"
author: "Marta Kołczyńska"
date: 2018-08-05T07:32:00
categories: ["SDR"]
tags: ["surveys", "SDR", "R", "cross-national research", "shiny", "plotly", "tutorial", "survey data harmonization"]
output: 
  blogdown::html_page:
    toc: true

---
&nbsp;  

In the [previous post](https://martakolczynska.netlify.com/post/sdr-exploration/) I wrote about downloading and exploring the [Survey Data Recycling (SDR), version 1.0 dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/VWGF5Q){target="_blank"}, which consists of selected harmonized variables from 22 survey projects, 1966-2013.

The [SDR project](dataharmonization.org){target="_blank"} will develop a website for browsing, subsetting, downloading, and visualizing data from the SDR project. This website is currently under construction. Meanwhile, I made a Shiny app with basic functionalities of the future on-line browsing and subsetting tool (also serves as its mock-up): https://mkolczynska.shinyapps.io/sdr_data_browser/. 

*Please note that this Shiny app is not a final product, so it might still have some issues. This applies most likely to the design though; the accuracy of the information displayed has been thoroughly checked.*

*Any recommendations regarding the functionalities or design of the SDR selection tool are very welcome!*

### Instructions

To select a subset of the SDR masterfile, choose the variables that you would be interested in using,  countries/world regions, survey projects, and the year range of interest.

If you select one of the variables in the "political engagement" group (participation in demonstrations or signing petitions), you will additionally have an option to choose the number of years the question asked about, e.g. "Have you participated in a demonstrations in the last year?" versus "Have you participated in the last 3 years?". "Ever" means that the the original survey question did not mention any time restriction. 


**Tabs:**

**Info page**: Instructions and references.

**Coverage table**: Availability of surveys meeting selected criteria (variables, countries, years, and projects) by country and year.

**Coverage map**: Availability of surveys meeting selected criteria (variables, countries, years, and projects) plotted on a world map.

**Project contributions table**: 'Coverage table' showing unique contributions of survey projects - to dostinguish the projects that contribute a lot of country-years from those that contribute a few (and possibly redundant ones).

**Survey list**: List of national surveys that meet the user's criteria with selected characteristics (e.g., sample size, quality indicators).

&nbsp;  

### References

*SDR Data and documentation:*

Slomczynski, Kazimierz M., J. Craig Jenkins, Irina Tomescu-Dubrow, Marta Kolczynska, Ilona Wysmulek, Olena Oleksiyenko, Przemek Powalko, Marcin W. Zielinski. 2017. “SDR Master Box.” https://doi.org/10.7910/DVN/VWGF5Q, Harvard Dataverse, V1, UNF:6:HIWud4wueVRsU8wTN+lySg==

*Software:*

R Core Team. 2018. R: A language and environment for statistical computing. R Foundation for Statistical Computing, Vienna, Austria. https://www.R-project.org/.

R packages: `shiny plotly readstata13 Hmisc labelled plyr dplyr shinyTree janitor DT Rcpp digest`